# /etc/rsyslog.conf
# Load necessary modules
module(load="imuxsock")   # For local system logging

# Do not load imklog since it cannot access /proc/kmsg in Docker
# module(load="imklog" permitnonkernelfacility="on")

# Log all messages to a file
*.* /var/log/syslog
