version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./frontend:/app/frontend/
      - node_modules:/app/frontend/node_modules/
    ports:
      - "9300:5173"
    command: npm run dev

  type-check:
    build:
      context: ./frontend
      dockerfile: no-alpine.Dockerfile
    volumes:
      - ./frontend:/app/frontend/
      - node_modules:/app/frontend/node_modules/
    command: /bin/bash -c 'script -q -c "npm run type-check:watch" /dev/null'

  unit-test:
    build:
      context: ./frontend
      dockerfile: no-alpine.Dockerfile
    environment:
      - FORCE_COLOR=1
    volumes:
      - ./frontend:/app/frontend/
      - node_modules_test:/app/frontend/node_modules/
    command: /bin/bash -c 'stdbuf -oL npm run test:unit | sed -r "s/\x1bc|\x1b\[H\x1b\[J|\x1b\[H\x1b\[2J|\x1b\[2J|\x1b\[3J|\x0c//g"'

  backend:
    build:
      context: ./python
      dockerfile: backend.Dockerfile
    volumes:
      - ./python/backend:/app/backend
      - ./python/shared:/app/shared
    env_file:
      - .env.mongodb
    ports:
      - "9301:5000"
    depends_on:
      - mongodb
    command: python3 develop.py
    restart: unless-stopped

  flask-test:
    build:
      context: ./python
      dockerfile: testing.Dockerfile
    volumes:
      - ./python/testing:/app/testing
      - ./python/backend:/app/backend
      - ./python/shared:/app/shared
    environment:
      - FORCE_COLOR=1
    env_file:
      - .env.mongodb
    depends_on:
      - mongodb
    command: ptw backend/


  mongodb:
    image: mongo:7.0.4
    ports:
      - "27017:27017"
    env_file:
      - .env.mongodb
    volumes:
      - ./database/mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

  scheduler:
    build:
      context: ./python
      dockerfile: scheduler.Dockerfile
    env_file:
      - .env.mongodb
    volumes:
      - ./python/scheduler:/app/scheduler
      - ./python/shared:/app/shared
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express:latest
    ports:
      - "9302:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb

  # nosqlclient:
  #   image: mongoclient/mongoclient:latest
  #   platform: linux/amd64
  #   environment:
  #     MONGOCLIENT_AUTH: "false"
  #     MONGO_URL: "mongodb://root:example@mongodb:27017"
  #   ports:
  #     - "9303:3000"
  #   depends_on:
  #     - mongodb

  backup:
    build:
      context: ./database
      dockerfile: backup.Dockerfile
    volumes:
      - ./database/scripts:/scripts
      - ./database/backups:/backups  # Local directory to store backups
    env_file:
      - .env.mongodb
    depends_on:
      - mongodb

volumes:
  node_modules:
  node_modules_test:
