version: '3'

services:
  frontend-build:
    build:
      context: ./frontend
    volumes:
      - frontend-dist:/app/frontend/dist

  backend:
    build:
      context: ./python
      dockerfile: backend.Dockerfile
    env_file:
      - .env.mongodb
    depends_on:
      - mongodb
    command: gunicorn --capture-output --enable-stdio-inheritance -c /app/backend/gunicorn_config.py live:app

  mongodb:
    image: mongo:7.0.4
    env_file:
      - .env.mongodb
    volumes:
      - ./database/mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

  backup:
    build:
      context: ./database
      dockerfile: backup.Dockerfile
    env_file:
      - .env.mongodb
    volumes:
      - ./database/backups:/backups
    depends_on:
      - mongodb

  scheduler:
    build:
      context: ./python
      dockerfile: scheduler.Dockerfile
    env_file:
      - .env.mongodb
    depends_on:
      - mongodb

  webserver:
    build:
      context: ./nginx
    volumes:
      - frontend-dist:/usr/share/nginx/html
      - ./nginx/stage.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9300:80"
    depends_on:
      - frontend-build
      - backend

volumes:
  frontend-dist:
