services:
  frontend-build:
    build:
      context: ./frontend
    volumes:
      - frontend-dist:/dist
    command: >
      sh -c "echo 'Starting copy...' &&
             rm -rf /dist/* &&
             cp -r /app/frontend/dist/* /dist &&
             ls -l /dist &&
             echo 'Copied files to /dist'"

  backend:
    build:
      context: ./python
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
    command: gunicorn --capture-output --enable-stdio-inheritance -c /app/backend/gunicorn_config.py live:app
    restart: always

  mongodb:
    image: mongo:7.0.4
    env_file:
      - .env
    volumes:
      - /database/mongodb:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

  backup:
    build:
      context: ./database
      dockerfile: backup.Dockerfile
    env_file:
      - .env
    volumes:
      - /database/backups:/backups
      - /database/uploads:/uploads:ro
    depends_on:
      - mongodb

  scheduler:
    build:
      context: ./python
      dockerfile: scheduler.Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always

  webserver:
    build:
      context: ./nginx
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
      - certificates:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-build
      - backend
    restart: always


volumes:
  frontend-dist:
  certificates:
