map $request_uri $is_blacklisted_path {
    default 0;

    ~^/\.env$                      1;
    ~^/\.git                      1;
    ~^/DS_Store                   1;
    ~^/actuator                   1;
    ~^/server-status              1;
    ~^/debug                      1;
    ~^/ecp                        1;
    ~^/_all_dbs                   1;
    ~^/webui                      1;
    ~^/geoserver                  1;
    ~^/phpmyadmin                 1;
    ~^/wp-admin                   1;
    ~^/\.vscode                   1;
    ~^/\.idea                     1;
    ~^/vendor                     1;
    ~^/composer\.(json|lock)$     1;
    ~^/package\.json$             1;
    ~^/yarn\.lock$                1;
    ~^/config\.(yaml|yml)$        1;
}
