include conf.d/include/gzip.conf;
include conf.d/include/routes.conf;
include conf.d/include/blacklist.conf;
include conf.d/include/limits.conf;

server {
    listen 80;
    server_name www.international-reader.com;

    include conf.d/include/well-known.conf;

    return 301 https://www.international-reader.com$request_uri;
}

server {
    listen 80;
    server_name international-reader.com;

    include conf.d/include/well-known.conf;

    return 301 https://www.international-reader.com$request_uri;
}

server {
    listen 443 ssl;
    server_name international-reader.com;

    include conf.d/include/ssl.conf;

    return 301 https://www.international-reader.com$request_uri;
}

server {
    listen 443 ssl;
    server_name www.international-reader.com;

    include conf.d/include/ssl.conf;

    include conf.d/include/well-known.conf;
    include conf.d/include/api.conf;

    include conf.d/include/main.conf;
}