gzip on;
gzip_types application/json application/javascript text/javascript text/css text/xml application/xml application/xml+rss text/plain;
gzip_min_length 1024;
gzip_comp_level 7;
gzip_proxied any;
gzip_vary on;
