root /usr/share/nginx/html;
index index.html;

error_page 404 /index.html;

location = /index.html {
    internal;
    root /usr/share/nginx/html;
}

location ~* ^/(\.env|\.git|DS_Store|actuator|server-status|debug|ecp|_all_dbs) {
    limit_req zone=zone_ui burst=5 nodelay;
    return 404;
}

location / {
    limit_req zone=zone_ui burst=30 nodelay;
    try_files $uri $uri/ @spa;
}

location @spa {
    if ($is_whitelist_route = 0) {
        return 404;
    }
    limit_req zone=zone_ui burst=10 nodelay;
    try_files /index.html =404;
}
