root /usr/share/nginx/html;
index index.html;

error_page 404 /index.html;

location = /index.html {
    internal;
    root /usr/share/nginx/html;
}

if ($is_blacklisted_path) {
    return 403;
}

location / {
    limit_req zone=zone_ui burst=30 nodelay;
    try_files $uri $uri/ @spa;
}

location @spa {
    if ($is_whitelist_route = 0) {
        return 404;
    }
    limit_req zone=zone_ui burst=10 nodelay;
    try_files /index.html =404;
}
