include conf.d/include/gzip.conf;
include conf.d/include/routes.conf;
include conf.d/include/blacklist.conf;
include conf.d/include/limits.conf;

server {
    listen 80;

    include conf.d/include/api.conf;
    include conf.d/include/main.conf;
}
