include conf.d/include/map.conf;
include conf.d/include/gzip.conf;
include conf.d/include/limit.conf;

server {
    listen 80;

    include conf.d/include/api.conf;
    include conf.d/include/main.conf;
}
