Syslog                  yes
UMask                   002
Domain                  international-reader.com
KeyFile                 /etc/opendkim/keys/dkim.private
Selector                mail
Socket                  inet:8891@localhost
